# Generated by Django 3.0.7 on 2020-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datapoint",
            name="response_message_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
