# Generated by Django 3.0.7 on 2021-01-06 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sms", "0005_user_logged_in_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="logged_in_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
