# Generated by Django 4.1.7 on 2023-04-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sms", "0006_auto_20210105_2025"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="callback",
            field=models.CharField(
                blank=True,
                choices=[("create_prayer_snippet", "create_prayer_snippet")],
                help_text="If defined, then this represents a callback function that we should trigger when we create a DataPoint for this question. The signature of the callback is `callback(data_point: DataPoint)`.",
                max_length=100,
                null=True,
            ),
        ),
    ]
