# Generated by Django 5.2.9 on 2025-12-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0008_alter_question_callback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datapoint",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Data Point",
                "verbose_name_plural": "Data Points",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["text"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "SMS User",
                "verbose_name_plural": "SMS Users",
            },
        ),
    ]
