# Generated by Django 2.1 on 2019-05-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="album_released_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
