# Generated by Django 5.2.9 on 2025-12-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0008_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bestof",
            options={
                "ordering": ["-end_date"],
                "verbose_name": "Best Of",
                "verbose_name_plural": "Best Of Lists",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="music",
            options={
                "ordering": ["-reviewed_at"],
                "verbose_name": "Album",
                "verbose_name_plural": "Albums",
            },
        ),
        migrations.AlterModelOptions(
            name="musician",
            options={
                "ordering": ["name"],
                "verbose_name": "Musician",
                "verbose_name_plural": "Musicians",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["name"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AddIndex(
            model_name="music",
            index=models.Index(
                fields=["-reviewed_at"], name="music_music_reviewe_c9307d_idx"
            ),
        ),
    ]
