# Generated by Django 5.2.9 on 2026-01-19 18:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("icon", models.CharField(help_text="Unicode emoji", max_length=10)),
                (
                    "serving_size",
                    models.CharField(
                        help_text='e.g., "1 oz", "1 dried fig"', max_length=50
                    ),
                ),
                (
                    "calories_per_serving",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in grid display"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Show in tracking grid"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Food",
                "verbose_name_plural": "Foods",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Consumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Number of servings",
                        max_digits=5,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_tracking.food",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumption",
                "verbose_name_plural": "Consumptions",
                "ordering": ["-consumed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-consumed_at"],
                        name="food_tracki_user_id_1fbf88_idx",
                    )
                ],
            },
        ),
    ]
