# Generated by Django 5.2.9 on 2026-01-19 18:45

from decimal import Decimal

from django.db import migrations


def add_initial_foods(apps, schema_editor):
    """Add initial food items."""
    Food = apps.get_model("food_tracking", "Food")

    initial_foods = [
        {
            "name": "Pecans",
            "icon": "🌰",
            "serving_size": "1 oz",
            "calories_per_serving": Decimal("196.00"),
            "display_order": 1,
        },
        {
            "name": "Cashews",
            "icon": "🌙",
            "serving_size": "1 oz",
            "calories_per_serving": Decimal("157.00"),
            "display_order": 2,
        },
        {
            "name": "Peanuts",
            "icon": "🥜",
            "serving_size": "1 oz",
            "calories_per_serving": Decimal("161.00"),
            "display_order": 3,
        },
        {
            "name": "Dried Figs",
            "icon": "🫐",
            "serving_size": "1 dried fig",
            "calories_per_serving": Decimal("20.00"),
            "display_order": 4,
        },
    ]

    for food_data in initial_foods:
        Food.objects.get_or_create(name=food_data["name"], defaults=food_data)


def remove_initial_foods(apps, schema_editor):
    """Remove initial food items (reverse migration)."""
    Food = apps.get_model("food_tracking", "Food")
    Food.objects.filter(
        name__in=["Pecans", "Cashews", "Peanuts", "Dried Figs"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_foods, remove_initial_foods),
    ]
