# Generated by Django 5.2.9 on 2026-01-19 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0002_add_initial_foods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumption",
            name="consumed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
