# Generated by Django 5.2.9 on 2026-06-15 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0003_remove_redundant_consumed_at_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consumption",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stored calories for ad-hoc entries (no Food reference).",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="consumption",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Free-text food description for ad-hoc (AI/recipe) entries.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="consumption",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="food_tracking.food",
            ),
        ),
        migrations.CreateModel(
            name="CalorieTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_calorie_target",
                    models.PositiveIntegerField(
                        default=2000,
                        help_text="Calories the user aims to stay within each day.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Calorie Target",
                "verbose_name_plural": "Calorie Targets",
                "ordering": ["user__username"],
            },
        ),
    ]
