# Generated by Django 5.2.9 on 2026-06-21 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0004_consumption_calories_consumption_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActiveCalories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The day these active calories were burned."
                    ),
                ),
                (
                    "active_calories",
                    models.PositiveIntegerField(
                        help_text="Apple Watch active (Move ring) calories for the day."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Active Calories",
                "verbose_name_plural": "Daily Active Calories",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
