# Generated by Django 5.2.9 on 2026-06-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracking", "0005_dailyactivecalories"),
    ]

    operations = [
        migrations.AddField(
            model_name="calorietarget",
            name="goal_deficit",
            field=models.PositiveIntegerField(
                default=500,
                help_text="Daily calorie deficit to aim for, subtracted from the budget.",
            ),
        ),
        migrations.AlterField(
            model_name="calorietarget",
            name="daily_calorie_target",
            field=models.PositiveIntegerField(
                default=2000,
                help_text="Resting base rate (e.g. RMR) the budget is built on top of.",
            ),
        ),
    ]
