# Generated by Django 4.1.13 on 2024-04-28 13:22

import datetime

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_end_text_sent_date",
            field=models.DateField(default=datetime.date(2021, 1, 1)),
        ),
        migrations.AddField(
            model_name="user",
            name="last_start_text_sent_date",
            field=models.DateField(default=datetime.date(2021, 1, 1)),
        ),
        migrations.CreateModel(
            name="DailyCheckin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "possible_focus_areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response_message_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="daily_goals.user",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="dailycheckin",
            index=models.Index(
                fields=["user", "-created_at"], name="daily_goals_user_id_3fe21a_idx"
            ),
        ),
    ]
