# Generated by Django 4.1.13 on 2024-05-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_goals", "0003_dailycheckin_chosen_focus_areas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_prompt",
            field=models.TextField(default=""),
        ),
    ]
