# Generated by Django 4.1.13 on 2024-05-06 03:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("daily_goals", "0004_user_ai_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="possible_focus_areas",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), blank=True, size=None
            ),
        ),
    ]
