# Generated by Django 5.2.9 on 2025-12-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("daily_goals", "0005_alter_user_possible_focus_areas"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailycheckin",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Daily Check-in",
                "verbose_name_plural": "Daily Check-ins",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Daily Goals User",
                "verbose_name_plural": "Daily Goals Users",
            },
        ),
    ]
