# Generated by Django 3.2.13 on 2023-01-08 17:59

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the snippet, which becomes part of the prayer.')),
                ('type', models.CharField(choices=[('1', 'GRATITUDE'), ('2', 'REQUEST'), ('3', 'PRAISE')], help_text='The type of snippet.', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this snippet expires.', null=True)),
                ('weighting', models.SmallIntegerField(blank=True, default=1, help_text='The value of this snippet from 1 to 10.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='The name of the prayer.')),
                ('next_generation_time', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0))),
                ('generation_cadence', models.DurationField(blank=True, default=datetime.timedelta(days=1))),
                ('generation_variance', models.DurationField(blank=True, default=datetime.timedelta(seconds=21600))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schema', models.TextField(help_text='The schema that we use to generate the prayer. The schema consists of Markdown with special markers in it to indicate where we should insert a prayer snippet. Write: {{ GRATITUDE, 3 }} to indicate that we should indicate three gratitude snippets. You must follow this syntax exactly of snippet type, comma, number of snippets. Otherwise a ValueError will be raised when we try to save the schema.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
