# Generated by Django 5.2.9 on 2025-12-28 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayer", "0002_prayersnippet_sms_data_point"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prayerschema",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Prayer Schema",
                "verbose_name_plural": "Prayer Schemas",
            },
        ),
        migrations.AlterModelOptions(
            name="prayersnippet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Prayer Snippet",
                "verbose_name_plural": "Prayer Snippets",
            },
        ),
        migrations.AlterField(
            model_name="prayersnippet",
            name="dynamic_weight",
            field=models.SmallIntegerField(
                blank=True,
                default=1,
                help_text="The dynamic weight of this snippet. Higher weights are more likely to be sampled.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
