#!/bin/bash

export DJANGO_SETTINGS_MODULE='website.settings.prod'

alias st='git status'
alias b='cd ..'
alias bb='b && b'
alias bbb='bb && b'
alias gow='cd ~/source'

source ~/venv/bin/activate
source ~/environment.env
