---
- hosts: all
  vars:
    username: ubuntu
    code_branch: master
  tasks:
    # Basics.
    - name: Change hostname
      become: yes
      hostname:
        name: web-server
  
    - name: Install basic packages
      become: yes
      apt:
        update_cache: yes
        name:
          - python3-pip
          - python3-dev
          - nginx
          - curl
          - libpq-dev
          - ipython
          - postgresql
          - postgresql-contrib

    - name: Set pip3 to be pip
      become: yes
      shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

    # Getting Django app working.
    - name: Clone repo
      git:
        repo: https://github.com/vpcarroll15/personal.git
        dest: /home/{{ username }}/source
        version: "{{ code_branch }}"
    
    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Install Django, gunicorn, other requirements
      pip:
        requirements: /home/{{ username }}/source/requirements.txt
        virtualenv: /home/{{ username }}/venv

    - name: Copy .bash_aliases to remote machine
      copy:
        src: bash_aliases
        dest: /home/{{ username }}/.bash_aliases

    - name: Copy environment.env to remote machine
      copy:
        src: encrypted_environment.env
        dest: /home/{{ username }}/environment.env
      tags: vault
    
    # Getting gunicorn working.
    - name: Install gunicorn socket file
      become: yes
      copy:
        src: gunicorn.socket
        dest: /etc/systemd/system/gunicorn.socket

    - name: Install gunicorn service file
      become: yes
      template:
        src: gunicorn.service
        dest: /etc/systemd/system/gunicorn.service

    - name: Enable and start gunicorn socket
      become: yes
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: gunicorn.socket
