---
# Details on how to do this came from:
# https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04
# https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-20-04
- hosts: all
  vars:
    username: ubuntu
    code_branch: master
  tasks:
    # Basics.
    - name: Change hostname
      become: yes
      hostname:
        name: web-server
      tags: basics

    - name: Get apt repo necessary for python 3.11 right now
      become: yes
      apt_repository:
        repo: ppa:deadsnakes/ppa
        validate_certs: no
        update_cache: yes
      tags: basics
  
    - name: Install basic packages
      become: yes
      apt:
        name:
          - python3.11
          - python3.11-dev
          - python3.11-venv
          - python3.11-distutils
          - nginx
          - curl
          - libpq-dev
          - postgresql
          - postgresql-contrib
      tags: basics

    - name: Define python to be python3.11
      become: yes
      file:
        src: /usr/bin/python3.11
        dest: /usr/bin/python
        state: link
      tags: basics

    # Getting Django app working.
    - name: Clone repo
      git:
        repo: https://github.com/vpcarroll15/personal.git
        dest: /home/{{ username }}/source
        version: "{{ code_branch }}"
      tags: django

    - name: Install Django, gunicorn, other requirements
      pip:
        requirements: /home/{{ username }}/source/requirements.txt
        virtualenv: /home/{{ username }}/venv
        virtualenv_python: python3.11
      tags: django

    - name: Copy .bash_aliases to remote machine
      copy:
        src: bash_aliases
        dest: /home/{{ username }}/.bash_aliases
      tags: django

    - name: Copy environment.env to remote machine
      copy:
        src: encrypted_environment.env
        dest: /home/{{ username }}/environment.env
      tags: vault
    
    - name: Copy file that makes it easy to migrate Django
      copy:
        src: migrate_environment
        dest: /home/{{ username }}/migrate_environment
        mode: '0755'
      tags: django

    # Getting gunicorn working.
    - name: Install gunicorn socket file
      become: yes
      copy:
        src: gunicorn.socket
        dest: /etc/systemd/system/gunicorn.socket
      tags: gunicorn

    - name: Install gunicorn service file
      become: yes
      template:
        src: gunicorn.service
        dest: /etc/systemd/system/gunicorn.service
      tags: gunicorn

    - name: Enable and start gunicorn socket
      become: yes
      systemd:
        state: started
        enabled: yes
        daemon_reload: yes
        name: gunicorn.socket
      tags: gunicorn

    - name: Restart gunicorn
      become: yes
      systemd:
        state: restarted
        name: gunicorn
      tags: gunicorn

    # Getting nginx working.
    - name: Copy in nginx config file
      become: yes
      template:
        src: nginx_config
        dest: /etc/nginx/sites-available/paulcarroll.site
        # We can't replace this because Let's Encrypt edits it later. We don't
        # want to substitute back in the thing that doesn't support SSL.
        force: no
      tags: nginx

    - name: Symlink nginx config file to make it "available"
      become: yes
      file:
        src: /etc/nginx/sites-available/paulcarroll.site
        dest: /etc/nginx/sites-enabled/paulcarroll.site
        state: link
      tags: nginx
    
      # We want to get that A security rating!
      # https://www.ssllabs.com/ssltest/analyze.html
    - name: Disallow TLS 1.0 and 1.1, which are allowed by default.
      become: yes
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: ssl_protocols
        line: "        ssl_protocols TLSv1.2 TLSv1.3;"
      tags: nginx, tls

    - name: Restart nginx
      become: yes
      systemd:
        name: nginx
        state: restarted
      tags: nginx

    - name: Copy SMS manager service
      become: yes
      become_user: root
      template:
        src: sms_manager.service
        dest: /etc/systemd/system/
      tags: sms

    - name: Enable and load sms_manager service
      become: yes
      become_user: root
      systemd:
        name: /etc/systemd/system/sms_manager.service
        enabled: yes
        daemon_reload: yes
      tags: sms

    - name: Restart sms_manager service
      become: yes
      become_user: root
      systemd:
        name: sms_manager.service
        state: restarted
      tags: sms
 
    - name: Copy email triggerer service
      become: yes
      become_user: root
      template:
        src: email_triggerer.service
        dest: /etc/systemd/system/
      tags: email

    - name: Enable and load email_triggerer service
      become: yes
      become_user: root
      systemd:
        name: /etc/systemd/system/email_triggerer.service
        enabled: yes
        daemon_reload: yes
      tags: email

    - name: Restart email_triggerer service
      become: yes
      become_user: root
      systemd:
        name: email_triggerer.service
        state: restarted
      tags: email
    
    # Getting Let's Encrypt working.
    - name: Install Certbot
      become: yes
      apt:
        name:
          - certbot
          - python3-certbot-nginx
      tags: encrypt

    - debug:
        msg: If this is your first time setting up this machine, run "sudo certbot --nginx -d paulcarroll.site -d www.paulcarroll.site"
      tags: encrypt
