# Generated by Django 3.0.3 on 2020-06-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0002_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavengerhunt',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scavengerhunttemplate',
            name='finished_message',
            field=models.TextField(blank=True, help_text='The user will read this if they complete your hunt.'),
        ),
    ]
