# Generated by Django 3.0.7 on 2020-07-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scavenger_hunt", "0009_auto_20200703_1819"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location", name="clue", field=models.TextField(blank=True),
        ),
    ]
