# Generated by Django 3.0.7 on 2020-09-17 20:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scavenger_hunt", "0012_auto_20200916_2042"),
    ]

    operations = [
        migrations.AddField(
            model_name="scavengerhunt",
            name="location_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
    ]
