# Generated by Django 3.0.7 on 2020-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scavenger_hunt", "0013_scavengerhunt_location_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="hint",
            field=models.TextField(blank=True, null=True),
        ),
    ]
