# Generated by Django 3.0.7 on 2020-11-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0014_location_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavengerhunttemplate',
            name='skip_all_checks',
            field=models.BooleanField(default=False),
        ),
    ]
