# Generated by Django 3.2.7 on 2022-04-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavenger_hunt', '0017_location_solutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='solution',
        ),
    ]
