# Generated by Django 5.2.9 on 2025-12-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scavenger_hunt", "0018_remove_location_solution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="scavengerhunt",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Scavenger Hunt",
                "verbose_name_plural": "Scavenger Hunts",
            },
        ),
        migrations.AlterModelOptions(
            name="scavengerhunttemplate",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Scavenger Hunt Template",
                "verbose_name_plural": "Scavenger Hunt Templates",
            },
        ),
    ]
